const GUILD_ID = process.env.GUILD_ID;
const GENERAL_CHANNEL_ID = process.env.GENERAL_CHANNEL_ID;
const ONBOARDING_CHANNEL = process.env.ONBOARDING_CHANNEL;

const FRONTEND_DEVELOPER_MESSAGE = process.env.FRONTEND_DEVELOPER_MESSAGE;
const BACKEND_DEVELOPER_MESSAGE = process.env.BACKEND_DEVELOPER_MESSAGE;
const PRODUCT_DESIGNER_MESSAGE = process.env.PRODUCT_DESIGNER_MESSAGE;
const PRODUCT_MANAGER_MESSAGE = process.env.PRODUCT_MANAGER_MESSAGE;
const VERIFY_USER_MESSAGE = process.env.VERIFY_USER_MESSAGE;
export {
  GUILD_ID,
  GENERAL_CHANNEL_ID,
  ONBOARDING_CHANNEL,
  FRONTEND_DEVELOPER_MESSAGE,
  BACKEND_DEVELOPER_MESSAGE,
  PRODUCT_DESIGNER_MESSAGE,
  PRODUCT_MANAGER_MESSAGE,
  VERIFY_USER_MESSAGE,
};
